# Generated by Django 3.0b1 on 2019-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('event_date', models.DateField()),
                ('storage', models.CharField(choices=[('n', 'Normal'), ('c', 'Fridge'), ('f', 'Frezzer'), ('o', 'Other')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
